# Generated by Django 6.0.6 on 2026-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0002_payment_commission_amount_payment_vendor_earning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note regarding the payout', null=True),
        ),
    ]
