# Generated by Django 6.0.6 on 2026-06-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0003_payout_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='trx_id',
            field=models.CharField(blank=True, help_text='Transaction ID', max_length=100, null=True),
        ),
    ]
