# Generated by Django 6.0.6 on 2026-06-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0004_payout_trx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
