# Generated by Django 6.0.6 on 2026-06-13 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(limit_choices_to={'is_active': True, 'name': 'role'}, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='lookup.lookup')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
