# Generated by Django 6.0.6 on 2026-06-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_category_admintag_is_trending_admintag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
