# Generated by Django 6.0.6 on 2026-06-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount owed to the vendor', max_digits=12),
        ),
    ]
