# Generated by Django 6.0.6 on 2026-06-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('connected', 'Connected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('timeout', 'Timeout')], default='searching', max_length=20),
        ),
    ]
