# Generated by Django 6.0.6 on 2026-06-22 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0002_alter_callsession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='rejected_vendors',
            field=models.ManyToManyField(blank=True, related_name='rejected_calls', to=settings.AUTH_USER_MODEL),
        ),
    ]
