# Generated by Django 6.0.6 on 2026-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0003_callsession_rejected_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callsession',
            old_name='accepted_by',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='callsession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
