# Generated by Django 6.0.6 on 2026-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_shortnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnote',
            name='product_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
