# Generated by Django 6.0.6 on 2026-06-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_is_confirm_invoice_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_confirmed_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
